[project]
name = "model-interface"
version = "0.1.2.dev1"
description = "Model interface for VLM HyperBench"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
authors = [
   "VLMHyperBenchTeam <https://github.com/VLMHyperBenchTeam>",
   "Anton Shiryaev <med.phisiker@gmail.com>"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["model_interface"]
